version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - store-service
      - user-service

  store-service:
    build:
      context: ./store-service
    ports:
      - "3000:3000"

  user-service:
    build:
      context: ./user-service
    ports:
      - "3001:3000"
    environment:
      MYSQL_HOST: mysql-service
      MYSQL_USER: root
      MYSQL_PASSWORD: '@Rz76922'
      MYSQL_DB: jira_v2
    depends_on:
      - mysql-service

  mysql-service:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '@Rz76922'
      MYSQL_DATABASE: jira_v2
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb-service:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
